# Generated by Django 3.1.7 on 2021-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='gov_id',
            field=models.ImageField(null=True, upload_to='gov_ids'),
        ),
    ]
