# Generated by Django 3.1.7 on 2021-07-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_taker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='gov_id',
        ),
        migrations.AddField(
            model_name='register',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=20),
            preserve_default=False,
        ),
    ]
