# Generated by Django 3.1.7 on 2021-07-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210709_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
    ]
