# Generated by Django 3.1.7 on 2021-05-02 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('income_ceiling', models.TextField()),
                ('value_of_scholarship', models.TextField()),
                ('how_and_when_to_apply', models.TextField()),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='taker_image')),
                ('video', models.FileField(upload_to='taker_video')),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('isbn_no', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('published', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('image1', models.ImageField(upload_to='book_picks')),
                ('image2', models.ImageField(upload_to='book_picks')),
                ('image3', models.ImageField(upload_to='book_picks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card', models.ImageField(upload_to='adhar_cards')),
                ('USN', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('caste', models.CharField(choices=[('hindu', 'hindu'), ('muslim', 'muslim'), ('general', 'general'), ('sc', 'sc'), ('st', 'st')], max_length=50)),
                ('merit', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('reject', 'reject'), ('approve', 'approve'), ('pending', 'pending')], default='pending', max_length=20)),
                ('college_id_card', models.ImageField(null=True, upload_to='id_cards')),
                ('certificate', models.ImageField(null=True, upload_to='certificates')),
                ('income_certificates', models.ImageField(null=True, upload_to='income_certificates')),
                ('marks_cards_10th', models.ImageField(null=True, upload_to='marks_cards_10th')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
