# Generated by Django 3.1.7 on 2021-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taker_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taker',
            name='video',
            field=models.ImageField(upload_to='taker_image'),
        ),
    ]
